[package]
name = "rust_example_project"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_example_project"
crate-type = ["staticlib"]

[dependencies]
csp_sys = {path = "../csp_sys"}
slash_sys = {path = "../slash_sys"}